/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinTeamRouteImport } from './routes/join-team'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhysioIndexRouteImport } from './routes/physio.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PhysioLogRouteImport } from './routes/physio.log'
import { Route as PhysioCaseRouteImport } from './routes/physio.case'
import { Route as DevDiagnosticsRouteImport } from './routes/dev.diagnostics'
import { Route as CoachWellnessRouteImport } from './routes/coach.wellness'
import { Route as CoachProgramRouteImport } from './routes/coach.program'
import { Route as CoachGamesRouteImport } from './routes/coach.games'
import { Route as AthleteWorkoutRouteImport } from './routes/athlete.workout'
import { Route as AthleteWellnessRouteImport } from './routes/athlete.wellness'
import { Route as AthleteProgressRouteImport } from './routes/athlete.progress'
import { Route as AthletePostWorkoutRouteImport } from './routes/athlete.post-workout'
import { Route as AthleteInjuryRouteImport } from './routes/athlete.injury'
import { Route as AthleteHistoryRouteImport } from './routes/athlete.history'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminInjuriesRouteImport } from './routes/admin.injuries'
import { Route as CoachAthleteAthleteIdRouteImport } from './routes/coach.athlete.$athleteId'

const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTeamRoute = JoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioIndexRoute = PhysioIndexRouteImport.update({
  id: '/physio/',
  path: '/physio/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioLogRoute = PhysioLogRouteImport.update({
  id: '/physio/log',
  path: '/physio/log',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioCaseRoute = PhysioCaseRouteImport.update({
  id: '/physio/case',
  path: '/physio/case',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiagnosticsRoute = DevDiagnosticsRouteImport.update({
  id: '/dev/diagnostics',
  path: '/dev/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachWellnessRoute = CoachWellnessRouteImport.update({
  id: '/coach/wellness',
  path: '/coach/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramRoute = CoachProgramRouteImport.update({
  id: '/coach/program',
  path: '/coach/program',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachGamesRoute = CoachGamesRouteImport.update({
  id: '/coach/games',
  path: '/coach/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteWorkoutRoute = AthleteWorkoutRouteImport.update({
  id: '/athlete/workout',
  path: '/athlete/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteWellnessRoute = AthleteWellnessRouteImport.update({
  id: '/athlete/wellness',
  path: '/athlete/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProgressRoute = AthleteProgressRouteImport.update({
  id: '/athlete/progress',
  path: '/athlete/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePostWorkoutRoute = AthletePostWorkoutRouteImport.update({
  id: '/athlete/post-workout',
  path: '/athlete/post-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteInjuryRoute = AthleteInjuryRouteImport.update({
  id: '/athlete/injury',
  path: '/athlete/injury',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteHistoryRoute = AthleteHistoryRouteImport.update({
  id: '/athlete/history',
  path: '/athlete/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInjuriesRoute = AdminInjuriesRouteImport.update({
  id: '/admin/injuries',
  path: '/admin/injuries',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAthleteAthleteIdRoute = CoachAthleteAthleteIdRouteImport.update({
  id: '/coach/athlete/$athleteId',
  path: '/coach/athlete/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/admin/injuries': typeof AdminInjuriesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/athlete/history': typeof AthleteHistoryRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/post-workout': typeof AthletePostWorkoutRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/wellness': typeof AthleteWellnessRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/games': typeof CoachGamesRoute
  '/coach/program': typeof CoachProgramRoute
  '/coach/wellness': typeof CoachWellnessRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/physio/case': typeof PhysioCaseRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athlete/$athleteId': typeof CoachAthleteAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/admin/injuries': typeof AdminInjuriesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/athlete/history': typeof AthleteHistoryRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/post-workout': typeof AthletePostWorkoutRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/wellness': typeof AthleteWellnessRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/games': typeof CoachGamesRoute
  '/coach/program': typeof CoachProgramRoute
  '/coach/wellness': typeof CoachWellnessRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/physio/case': typeof PhysioCaseRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/coach': typeof CoachIndexRoute
  '/physio': typeof PhysioIndexRoute
  '/coach/athlete/$athleteId': typeof CoachAthleteAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/admin/injuries': typeof AdminInjuriesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/athlete/history': typeof AthleteHistoryRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/post-workout': typeof AthletePostWorkoutRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/wellness': typeof AthleteWellnessRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/games': typeof CoachGamesRoute
  '/coach/program': typeof CoachProgramRoute
  '/coach/wellness': typeof CoachWellnessRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/physio/case': typeof PhysioCaseRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athlete/$athleteId': typeof CoachAthleteAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/help'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/system-status'
    | '/admin/injuries'
    | '/admin/invites'
    | '/admin/sessions'
    | '/admin/teams'
    | '/athlete/history'
    | '/athlete/injury'
    | '/athlete/post-workout'
    | '/athlete/progress'
    | '/athlete/wellness'
    | '/athlete/workout'
    | '/coach/games'
    | '/coach/program'
    | '/coach/wellness'
    | '/dev/diagnostics'
    | '/physio/case'
    | '/physio/log'
    | '/admin/'
    | '/athlete/'
    | '/coach/'
    | '/physio/'
    | '/coach/athlete/$athleteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/help'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/system-status'
    | '/admin/injuries'
    | '/admin/invites'
    | '/admin/sessions'
    | '/admin/teams'
    | '/athlete/history'
    | '/athlete/injury'
    | '/athlete/post-workout'
    | '/athlete/progress'
    | '/athlete/wellness'
    | '/athlete/workout'
    | '/coach/games'
    | '/coach/program'
    | '/coach/wellness'
    | '/dev/diagnostics'
    | '/physio/case'
    | '/physio/log'
    | '/admin'
    | '/athlete'
    | '/coach'
    | '/physio'
    | '/coach/athlete/$athleteId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/help'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/system-status'
    | '/admin/injuries'
    | '/admin/invites'
    | '/admin/sessions'
    | '/admin/teams'
    | '/athlete/history'
    | '/athlete/injury'
    | '/athlete/post-workout'
    | '/athlete/progress'
    | '/athlete/wellness'
    | '/athlete/workout'
    | '/coach/games'
    | '/coach/program'
    | '/coach/wellness'
    | '/dev/diagnostics'
    | '/physio/case'
    | '/physio/log'
    | '/admin/'
    | '/athlete/'
    | '/coach/'
    | '/physio/'
    | '/coach/athlete/$athleteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CreateTeamRoute: typeof CreateTeamRoute
  FeedRoute: typeof FeedRoute
  HelpRoute: typeof HelpRoute
  JoinTeamRoute: typeof JoinTeamRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SystemStatusRoute: typeof SystemStatusRoute
  AdminInjuriesRoute: typeof AdminInjuriesRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AthleteHistoryRoute: typeof AthleteHistoryRoute
  AthleteInjuryRoute: typeof AthleteInjuryRoute
  AthletePostWorkoutRoute: typeof AthletePostWorkoutRoute
  AthleteProgressRoute: typeof AthleteProgressRoute
  AthleteWellnessRoute: typeof AthleteWellnessRoute
  AthleteWorkoutRoute: typeof AthleteWorkoutRoute
  CoachGamesRoute: typeof CoachGamesRoute
  CoachProgramRoute: typeof CoachProgramRoute
  CoachWellnessRoute: typeof CoachWellnessRoute
  DevDiagnosticsRoute: typeof DevDiagnosticsRoute
  PhysioCaseRoute: typeof PhysioCaseRoute
  PhysioLogRoute: typeof PhysioLogRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  PhysioIndexRoute: typeof PhysioIndexRoute
  CoachAthleteAthleteIdRoute: typeof CoachAthleteAthleteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-team': {
      id: '/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/': {
      id: '/physio/'
      path: '/physio'
      fullPath: '/physio/'
      preLoaderRoute: typeof PhysioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/athlete'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/log': {
      id: '/physio/log'
      path: '/physio/log'
      fullPath: '/physio/log'
      preLoaderRoute: typeof PhysioLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/case': {
      id: '/physio/case'
      path: '/physio/case'
      fullPath: '/physio/case'
      preLoaderRoute: typeof PhysioCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diagnostics': {
      id: '/dev/diagnostics'
      path: '/dev/diagnostics'
      fullPath: '/dev/diagnostics'
      preLoaderRoute: typeof DevDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/wellness': {
      id: '/coach/wellness'
      path: '/coach/wellness'
      fullPath: '/coach/wellness'
      preLoaderRoute: typeof CoachWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/program': {
      id: '/coach/program'
      path: '/coach/program'
      fullPath: '/coach/program'
      preLoaderRoute: typeof CoachProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/games': {
      id: '/coach/games'
      path: '/coach/games'
      fullPath: '/coach/games'
      preLoaderRoute: typeof CoachGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/workout': {
      id: '/athlete/workout'
      path: '/athlete/workout'
      fullPath: '/athlete/workout'
      preLoaderRoute: typeof AthleteWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/wellness': {
      id: '/athlete/wellness'
      path: '/athlete/wellness'
      fullPath: '/athlete/wellness'
      preLoaderRoute: typeof AthleteWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/progress': {
      id: '/athlete/progress'
      path: '/athlete/progress'
      fullPath: '/athlete/progress'
      preLoaderRoute: typeof AthleteProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/post-workout': {
      id: '/athlete/post-workout'
      path: '/athlete/post-workout'
      fullPath: '/athlete/post-workout'
      preLoaderRoute: typeof AthletePostWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/injury': {
      id: '/athlete/injury'
      path: '/athlete/injury'
      fullPath: '/athlete/injury'
      preLoaderRoute: typeof AthleteInjuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/history': {
      id: '/athlete/history'
      path: '/athlete/history'
      fullPath: '/athlete/history'
      preLoaderRoute: typeof AthleteHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/injuries': {
      id: '/admin/injuries'
      path: '/admin/injuries'
      fullPath: '/admin/injuries'
      preLoaderRoute: typeof AdminInjuriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/athlete/$athleteId': {
      id: '/coach/athlete/$athleteId'
      path: '/coach/athlete/$athleteId'
      fullPath: '/coach/athlete/$athleteId'
      preLoaderRoute: typeof CoachAthleteAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CreateTeamRoute: CreateTeamRoute,
  FeedRoute: FeedRoute,
  HelpRoute: HelpRoute,
  JoinTeamRoute: JoinTeamRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SystemStatusRoute: SystemStatusRoute,
  AdminInjuriesRoute: AdminInjuriesRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AthleteHistoryRoute: AthleteHistoryRoute,
  AthleteInjuryRoute: AthleteInjuryRoute,
  AthletePostWorkoutRoute: AthletePostWorkoutRoute,
  AthleteProgressRoute: AthleteProgressRoute,
  AthleteWellnessRoute: AthleteWellnessRoute,
  AthleteWorkoutRoute: AthleteWorkoutRoute,
  CoachGamesRoute: CoachGamesRoute,
  CoachProgramRoute: CoachProgramRoute,
  CoachWellnessRoute: CoachWellnessRoute,
  DevDiagnosticsRoute: DevDiagnosticsRoute,
  PhysioCaseRoute: PhysioCaseRoute,
  PhysioLogRoute: PhysioLogRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthleteIndexRoute: AthleteIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  PhysioIndexRoute: PhysioIndexRoute,
  CoachAthleteAthleteIdRoute: CoachAthleteAthleteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
